import express from "express";
import PDFDocument from "pdfkit";
import { getSecurityReport, reportCsv } from "../services/reportService.js";

const router = express.Router();

function reportOptions(query) {
  return { range: query.range, start: query.start, end: query.end };
}

function filename(prefix) {
  return `${prefix}-${new Date().toISOString().slice(0, 10)}.${prefix === "sentinelx-security-report" ? "pdf" : "csv"}`;
}

router.get("/", async (req, res) => {
  try {
    const report = await getSecurityReport(reportOptions(req.query));
    res.json({ success: true, report: { ...report, alerts: undefined } });
  } catch (error) {
    res.status(error.statusCode || 500).json({ success: false, message: error.message || "Unable to generate report" });
  }
});

router.get("/export/csv", async (req, res) => {
  try {
    const report = await getSecurityReport(reportOptions(req.query));
    res.setHeader("Content-Type", "text/csv; charset=utf-8");
    res.setHeader("Content-Disposition", `attachment; filename="${filename("sentinelx-alerts")}"`);
    res.send(`\uFEFF${reportCsv(report)}`);
  } catch (error) {
    res.status(error.statusCode || 500).json({ success: false, message: error.message || "Unable to export CSV" });
  }
});

router.get("/export/pdf", async (req, res) => {
  try {
    const report = await getSecurityReport(reportOptions(req.query));
    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", `attachment; filename="${filename("sentinelx-security-report")}"`);

    const doc = new PDFDocument({ margin: 52, size: "A4" });
    doc.pipe(res);
    const title = "SENTINELX IDPS";
    doc.fillColor("#0891b2").fontSize(20).font("Helvetica-Bold").text(title, { align: "center" });
    doc.fillColor("#111827").fontSize(12).font("Helvetica").text("SECURITY INCIDENT REPORT", { align: "center" });
    doc.moveDown(1.5);
    doc.fillColor("#475569").fontSize(9).text(`Report period: ${new Date(report.period.start).toLocaleString()} - ${new Date(report.period.end).toLocaleString()}`);
    doc.moveDown();
    doc.fillColor("#111827").font("Helvetica-Bold").fontSize(13).text("Alert Summary");
    doc.moveDown(0.4).font("Helvetica").fontSize(10);
    const severity = Object.fromEntries(report.summary.severities.map((item) => [item.severity, item.count]));
    [["Total Alerts", report.summary.totalAlerts], ["Critical", severity.CRITICAL], ["High", severity.HIGH], ["Blocked", report.summary.blocked]].forEach(([label, value]) => doc.text(`${label.padEnd(22)} ${value}`));
    doc.moveDown().font("Helvetica-Bold").fontSize(13).text("Threat Distribution");
    doc.moveDown(0.4).font("Helvetica").fontSize(10);
    (report.threats.length ? report.threats : [{ label: "No alerts in this period", count: 0 }]).forEach((item) => doc.text(`${item.label.padEnd(22)} ${item.count}`));
    doc.moveDown().font("Helvetica-Bold").fontSize(13).text("Top Source IPs");
    doc.moveDown(0.4).font("Helvetica").fontSize(10);
    (report.topSources.length ? report.topSources : [{ sourceIp: "No source IPs in this period", count: 0 }]).forEach((item) => doc.text(`${item.sourceIp.padEnd(22)} ${item.count} alerts`));
    doc.moveDown(2).fillColor("#64748b").fontSize(8).text(`Generated by SentinelX IDPS on ${new Date().toLocaleString()}`, { align: "center" });
    doc.end();
  } catch (error) {
    if (!res.headersSent) res.status(error.statusCode || 500).json({ success: false, message: error.message || "Unable to export PDF" });
  }
});

export default router;
